source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios,'10.0'
target 'MonitoringAssistant_ZN' do

pod 'Alamofire', '~> 4.5'

pod 'SnapKit', '~> 3.2.0'
pod 'HandyJSON', '4.0.0-beta.1'
pod 'Kingfisher', '~> 4.0'

pod "ESPullToRefresh"

pod 'Charts'
pod 'ChartsRealm'

end
